[package]
name = "closures"
version = "0.1.0"
authors = ["etienne.goosse <etienne.goosse@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
